### ISSUE TITLE
BitString encapsulating Sequence of Integers

### ISSUE THREAD

**Issue by Spomky** [fgrosse/PHPASN1#47]
Hi,

I have RSA details `n` and `e` (modulo and exponent) from a plubic key.
I would like to convert these values into a PKCS#8 file, but a encounter some problems with Integer and BitString classes.

According to the specification and [this useful page](http://www.cryptopp.com/wiki/Keys_and_Formats#RSA_PublicKey), the sequence is:
```yml
Sequence:
    Sequence:
        ObjectIdentifier: 1.2.840.113549.1.1.1
        NullObject
    BitString:
        Sequence:
            Integer: n value
            Integer: e value
```

Hereafter my code:
```php
$result = new Sequence();
$oid_sequence = new Sequence();
$oid_sequence->addChild(new ObjectIdentifier('1.2.840.113549.1.1.1'));
$oid_sequence->addChild(new NullObject());
$result ->addChild($oid_sequence);

$key_sequence = new Sequence();
$n = "23048702444524490053025563207470260339027703388228696677413189217645523615585428278678890992016618560435...";
$e = "65537";
$key_sequence->addChild(new Integer($n));
$key_sequence->addChild(new Integer($e));

$key_bit_string = new BitString(???);
$result ->addChild($key_bit_string);
```

My questions are:
* It seems that the size calculated for `Integer($n)` is wrong. I get 2 but I should have 257. Is there a bug or am I wrong?
* How can I encapsulate my key sequence into the BitString object?
